deployment:
  nginx:
    image:
      repository: nginx
      tag: latest
  replicas: 4
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer