parameters:
- name: "serviceconnection"
  type: string
- name: "environment"
  type: string
  
jobs:
  - deployment: DeployInfraResources
    displayName: "Deploy Resources for: ${{parameters.environment}} environment"
    environment: "${{parameters.environment}}"
    strategy:
      runOnce:
        deploy:
          steps:                
            - task: AzureCLI@2
              displayName: "Deploy Infra" 
              inputs:
                azureSubscription: "${{parameters.serviceconnection}}"
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                workingDirectory: $(Pipeline.Workspace)
                inlineScript: |
                  $filename = "$(Pipeline.Workspace)/InfraPackage/infra/bicep/main.bicep"
                  $parametersfilename = "$(Pipeline.Workspace)/InfraPackage/infra/bicep/main.bicepparam"                 
                  Write-Host "STARTING DEPLOYMENT......."
                  
                  $validationResult = az deployment sub create --location uksouth --template-file $filename --parameters $parametersfilename
                  # if($validationResult.Contains("InvalidTemplate"))
                  # {
                  #   throw $validationResult
                  # }
                  Write-Output "Successfully validated $file.FullName"

            