apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart.fullname" . }}-service
  labels:
  {{- include "helmchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx
    {{- include "helmchart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}
